language: rust
rust:
  - stable
cache:
  cargo: true
  directories:
   - $HOME/deps
os: osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
script:
  - cargo build --verbose --all
  - cargo test --verbose --all

notifications:
webhooks:
  urls:
    - https://webhooks.gitter.im/e/c09595dea93d78afd940
  on_success: change
  on_failure: always
  on_start: never
