os: Visual Studio 2015

environment:
  global:
    CHANNEL: stable
    CRATE_NAME: spirv_cross
  matrix:
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\msys64\mingw64\bin;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - git submodule update --init --recursive

build_script:
  - cargo build --verbose --all --target %TARGET%

test_script:
  - cargo test --verbose --all --target %TARGET%

branches:
  only:
    - staging
    - trying
    - master
  except:
    - staging.tmp

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/8748eda7974203c7a542
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
